#[cfg(test)]
use crate::database::trait_::DatabaseTrait;
#[cfg(test)]
use crate::models::{Execution, Position, TradeHistory, UserWithRoles};
#[cfg(test)]
use anyhow::Result;
#[cfg(test)]
use chrono::{DateTime, Utc};
#[cfg(test)]
use mockall::automock;

// Create a mockable trait that matches DatabaseTrait interface
// mockall will generate MockMockDatabaseTrait struct
#[cfg(test)]
#[automock]
#[async_trait::async_trait]
pub trait MockDatabaseTrait: Send + Sync {
    async fn insert_execution(&self, execution: &Execution) -> Result<()>;
    async fn query_recent_executions(&self, from_time: DateTime<Utc>) -> Result<Vec<Execution>>;
    async fn query_executions_paginated(
        &self,
        username: &str,
        page: i32,
        size: i32,
        symbol: Option<&str>,
    ) -> Result<Vec<Execution>>;
    async fn count_executions(&self, username: &str, symbol: Option<&str>) -> Result<i64>;
    async fn query_executions_by_symbol_all_users(
        &self,
        symbol: &str,
        page: i32,
        size: i32,
    ) -> Result<Vec<Execution>>;
    async fn count_executions_by_symbol_all_users(&self, symbol: &str) -> Result<i64>;
    async fn calculate_volume_by_symbol(
        &self,
        symbol: &str,
        from_time: DateTime<Utc>,
        to_time: DateTime<Utc>,
    ) -> Result<(i64, i64)>;
    async fn calculate_total_volume(
        &self,
        from_time: DateTime<Utc>,
        to_time: DateTime<Utc>,
    ) -> Result<(i64, i64)>;
    async fn upsert_position(&self, position: &Position) -> Result<()>;
    async fn query_position(&self, username: &str, symbol: &str) -> Result<Option<Position>>;
    async fn query_all_positions(&self, username: &str) -> Result<Vec<Position>>;
    async fn insert_trade_history(&self, trade_history: &TradeHistory) -> Result<()>;
    async fn query_trade_history(&self, username: &str) -> Result<Vec<TradeHistory>>;
    async fn query_trade_history_by_symbol(&self, username: &str, symbol: &str) -> Result<Vec<TradeHistory>>;
    async fn query_trade_history_by_cl_ord_id(&self, cl_ord_id: &str) -> Result<Vec<TradeHistory>>;
    async fn register_user(&self, username: &str, encoded_password: &str, roles: &[String]) -> Result<()>;
    async fn user_exists(&self, username: &str) -> Result<bool>;
    async fn load_user(&self, username: &str) -> Result<Option<UserWithRoles>>;
}

// Implement DatabaseTrait for the mock struct generated by mockall
#[cfg(test)]
#[async_trait::async_trait]
impl DatabaseTrait for MockMockDatabaseTrait {
    async fn insert_execution(&self, execution: &Execution) -> Result<()> {
        MockDatabaseTrait::insert_execution(self, execution).await
    }

    async fn query_recent_executions(&self, from_time: DateTime<Utc>) -> Result<Vec<Execution>> {
        MockDatabaseTrait::query_recent_executions(self, from_time).await
    }

    async fn query_executions_paginated(
        &self,
        username: &str,
        page: i32,
        size: i32,
        symbol: Option<&str>,
    ) -> Result<Vec<Execution>> {
        MockDatabaseTrait::query_executions_paginated(self, username, page, size, symbol).await
    }

    async fn count_executions(&self, username: &str, symbol: Option<&str>) -> Result<i64> {
        MockDatabaseTrait::count_executions(self, username, symbol).await
    }

    async fn query_executions_by_symbol_all_users(
        &self,
        symbol: &str,
        page: i32,
        size: i32,
    ) -> Result<Vec<Execution>> {
        MockDatabaseTrait::query_executions_by_symbol_all_users(self, symbol, page, size).await
    }

    async fn count_executions_by_symbol_all_users(&self, symbol: &str) -> Result<i64> {
        MockDatabaseTrait::count_executions_by_symbol_all_users(self, symbol).await
    }

    async fn calculate_volume_by_symbol(
        &self,
        symbol: &str,
        from_time: DateTime<Utc>,
        to_time: DateTime<Utc>,
    ) -> Result<(i64, i64)> {
        MockDatabaseTrait::calculate_volume_by_symbol(self, symbol, from_time, to_time).await
    }

    async fn calculate_total_volume(
        &self,
        from_time: DateTime<Utc>,
        to_time: DateTime<Utc>,
    ) -> Result<(i64, i64)> {
        MockDatabaseTrait::calculate_total_volume(self, from_time, to_time).await
    }

    async fn upsert_position(&self, position: &Position) -> Result<()> {
        MockDatabaseTrait::upsert_position(self, position).await
    }

    async fn query_position(&self, username: &str, symbol: &str) -> Result<Option<Position>> {
        MockDatabaseTrait::query_position(self, username, symbol).await
    }

    async fn query_all_positions(&self, username: &str) -> Result<Vec<Position>> {
        MockDatabaseTrait::query_all_positions(self, username).await
    }

    async fn insert_trade_history(&self, trade_history: &TradeHistory) -> Result<()> {
        MockDatabaseTrait::insert_trade_history(self, trade_history).await
    }

    async fn query_trade_history(&self, username: &str) -> Result<Vec<TradeHistory>> {
        MockDatabaseTrait::query_trade_history(self, username).await
    }

    async fn query_trade_history_by_symbol(&self, username: &str, symbol: &str) -> Result<Vec<TradeHistory>> {
        MockDatabaseTrait::query_trade_history_by_symbol(self, username, symbol).await
    }

    async fn query_trade_history_by_cl_ord_id(&self, cl_ord_id: &str) -> Result<Vec<TradeHistory>> {
        MockDatabaseTrait::query_trade_history_by_cl_ord_id(self, cl_ord_id).await
    }

    async fn register_user(&self, username: &str, encoded_password: &str, roles: &[String]) -> Result<()> {
        MockDatabaseTrait::register_user(self, username, encoded_password, roles).await
    }

    async fn user_exists(&self, username: &str) -> Result<bool> {
        MockDatabaseTrait::user_exists(self, username).await
    }

    async fn load_user(&self, username: &str) -> Result<Option<UserWithRoles>> {
        MockDatabaseTrait::load_user(self, username).await
    }
}

